### ISSUE TITLE
请问这个怎么破

### ISSUE THREAD

**Issue by bluecodecc** [lazysheep666/terminal_theme#2]
extends includes/layout.pug block content include includes/recent-posts.pug include includes/pagination.pug

**Comment by lazysheep666** [comment]
具体是啥问题。

**Comment by bluecodecc** [comment]
就是，我安好了hexo，装了您的这个主题，然后改了配置文件为这个主题，进入首页就是这个错误了

**Comment by lazysheep666** [comment]
你在你博客跟目录下 npm i -g hexo-render-pug 然后再试试

**Comment by bluecodecc** [comment]
执行了，还是这样

**Comment by bluecodecc** [comment]
是不是对hexo版本什么的有要求？请问你的运行环境是什么
